%YAML:1.0
---
front_camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 4.2213163849000000e+02, 0., 6.1282890504000000e+02, 0.,
       4.2110340889000003e+02, 5.4505656249000003e+02, 0., 0., 1. ]
front_dist_coeffs: !!opencv-matrix
   rows: 4
   cols: 1
   dt: d
   data: [ -7.0318530000000004e-02, 3.8750500000000001e-03,
       -3.3313900000000000e-03, 5.6406000000000002e-04 ]
front_extrinsic: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 9.9927711846659273e-01, 3.8239026748119499e-04,
       -3.8014395783525085e-02, 6.7543741800000001e-01,
       -2.3074826484304832e-02, -7.8858244712801207e-01,
       -6.1449595317163441e-01, 2.5089688299999999e+01,
       -3.0212462524964401e-02, 6.1492892098134366e-01,
       -7.8800357185034264e-01, 3.1777930500000000e+00, 0., 0., 0., 1. ]
front_resolution: !!opencv-matrix
   rows: 2
   cols: 1
   dt: i
   data: [ 1280, 1080 ]
left_camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 4.2060079304999999e+02, 0., 6.5054173852999998e+02, 0.,
       4.1894827187999999e+02, 5.2727178143000003e+02, 0., 0., 1. ]
left_dist_coeffs: !!opencv-matrix
   rows: 4
   cols: 1
   dt: d
   data: [ -6.5838279799999996e-02, -2.0072851300000001e-03,
       -3.7253569400000000e-04, 1.8185166800000000e-06 ]
left_extrinsic: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ -8.7861640319031320e-03, 9.9996139899417680e-01,
       -6.1993651388869697e-05, 1.5630896433059958e+00,
       8.0641390062680418e-01, 7.0488994676406458e-03,
       -5.9130950769639878e-01, 1.6166976122837589e+01,
       -5.9128624556763287e-01, -5.2453348704752378e-03,
       -8.0644470502609722e-01, 1.0551627498521926e+01, 0., 0., 0., 1. ]
left_resolution: !!opencv-matrix
   rows: 2
   cols: 1
   dt: i
   data: [ 1280, 1080 ]
back_camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 4.2261569350000002e+02, 0., 6.3246019501000001e+02, 0.,
       4.2127373079000000e+02, 5.4834673287999999e+02, 0., 0., 1. ]
back_dist_coeffs: !!opencv-matrix
   rows: 4
   cols: 1
   dt: d
   data: [ -6.5538609999999997e-02, -9.4857000000000003e-04,
       -1.5074800000000001e-03, 3.2499999999999999e-04 ]
back_extrinsic: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ -9.9961569887037793e-01, 1.5643986146837520e-02,
       -2.2884935423191165e-02, 1.0926695300000000e+00,
       2.5990637053307356e-02, 8.1600873502745164e-01,
       -5.7745496027349319e-01, 2.4630812400000000e+01,
       9.6406098069220028e-03, -5.7782783773052671e-01,
       -8.1610173911480843e-01, 6.6095784499999999e+00, 0., 0., 0., 1. ]
back_resolution: !!opencv-matrix
   rows: 2
   cols: 1
   dt: i
   data: [ 1280, 1080 ]
right_camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 4.2164203585000001e+02, 0., 6.4009362064000004e+02, 0.,
       4.2026647020000001e+02, 5.2905566314999999e+02, 0., 0., 1. ]
right_dist_coeffs: !!opencv-matrix
   rows: 4
   cols: 1
   dt: d
   data: [ -7.2897519999999993e-02, 1.2546290000000000e-02,
       -1.3004770000000001e-02, 3.6126600000000002e-03 ]
right_extrinsic: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 1.2089559135778360e-02, -9.9992618794429877e-01,
       -1.2088106077854377e-03, -5.7858187913265913e-02,
       -6.2729894402906761e-01, -6.6428964775053778e-03,
       -7.7875022102494840e-01, 1.7601090119578668e+01,
       7.7868470986652827e-01, 1.0173032466876619e-02,
       -6.2733295149426738e-01, 6.3063662215483012e+00, 0., 0., 0., 1. ]
right_resolution: !!opencv-matrix
   rows: 2
   cols: 1
   dt: i
   data: [ 1280, 1080 ]
